name = "aidesignerfrontend"
compatibility_date = "2023-02-07"

# This is the Workers Sites configuration to serve your static files
[build]
command = "npm run build"  # Your build command for Next.js or React

[site]
bucket = "./out"  # Path to the directory containing your static assets (for Next.js it's 'out')
entry-point = "workers-site.js"  # The worker script that handles serving static files
