name = "aidesignerfrontend"
compatibility_date = "2023-02-07"
main="./.next"

# The build command for Next.js (builds the app and exports static assets)
[build]
command = "npm run build"

# Workers Sites configuration to serve static assets
[site]
bucket = "./out"  # The directory containing static assets after running `next export`
