name = "aidesignerfrontend"
main = "./workers-site.js"  # The worker script that handles serving static files
compatibility_date = "2023-02-07"

# This is the Workers Sites configuration to serve your static files
[build]
command = "npm run build"  # Your build command (e.g., for Next.js or React)

[site]
bucket = "./out"  # This should be the directory where your static assets are after build (e.g., `out` for Next.js or `build` for React)
entry-point = "./app/layout.tsx"  # Entry point for your worker code, like `workers-site.js`